# Generated by Django 4.2.6 on 2023-10-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0003_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_canteen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CafeApp.canteen'),
        ),
    ]
