# Generated by Django 4.2.5 on 2023-11-01 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0004_orders_order_canteen'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderquantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CafeApp.items')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CafeApp.orders')),
            ],
        ),
    ]
