# Generated by Django 4.2.5 on 2023-11-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0006_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('PaymentLeft', 'PaymentLeft'), ('Received', 'Received'), ('InProgress', 'InProgress'), ('Delivered', 'Delivered'), ('AddedToCart', 'AddedToCart')], max_length=100, null=True),
        ),
    ]
