# Generated by Django 4.2.5 on 2023-11-13 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
        ('CafeApp', '0007_alter_orders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBlacklistedToken',
            fields=[
                ('blacklistedtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='token_blacklist.blacklistedtoken')),
            ],
            bases=('token_blacklist.blacklistedtoken',),
        ),
    ]
