# Generated by Django 4.2.5 on 2023-11-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0008_customblacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
