# Generated by Django 4.2.5 on 2023-11-18 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0009_items_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 18, 5, 41, 30, 545637)),
        ),
    ]
