# Generated by Django 4.2.5 on 2023-11-27 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0010_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 27, 10, 11, 40, 105803)),
        ),
    ]
