# Generated by Django 4.1.8 on 2023-12-02 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0011_canteen_is_verified_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteen',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 2, 14, 59, 42, 407259)),
        ),
    ]
