# Generated by Django 5.0.6 on 2024-06-13 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0012_alter_canteen_is_verified_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 13, 17, 40, 15, 847847)),
        ),
    ]
