# Generated by Django 5.0.6 on 2024-06-21 09:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0014_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 21, 15, 21, 46, 689320)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Canteen', 'Canteen'), ('Customer', 'Customer'), ('Supervisor', 'Supervisor')], max_length=100),
        ),
        migrations.CreateModel(
            name='supervisor',
            fields=[
                ('supervisor_id', models.AutoField(primary_key=True, serialize=False)),
                ('supervis', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CafeApp.profile')),
            ],
        ),
    ]
